/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface ParkingSlot {
  'id' : bigint,
  'lat' : number,
  'lng' : number,
  'contactInfo' : string,
  'createdAt' : bigint,
  'isAvailable' : boolean,
  'description' : string,
  'ownerPin' : string,
  'address' : string,
  'slotNumber' : string,
  'apartmentName' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addSlot' : ActorMethod<
    [string, string, string, string, number, number, string, string],
    bigint
  >,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteSlot' : ActorMethod<[bigint, string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getSingleSlot' : ActorMethod<[bigint], [] | [ParkingSlot]>,
  'getSlotCount' : ActorMethod<[], bigint>,
  'getSlots' : ActorMethod<[boolean], Array<ParkingSlot>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'seedDemoSlots' : ActorMethod<[], undefined>,
  'toggleSlotAvailability' : ActorMethod<[bigint, string], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];