/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const ParkingSlot = IDL.Record({
  'id' : IDL.Nat,
  'lat' : IDL.Float64,
  'lng' : IDL.Float64,
  'contactInfo' : IDL.Text,
  'createdAt' : IDL.Int,
  'isAvailable' : IDL.Bool,
  'description' : IDL.Text,
  'ownerPin' : IDL.Text,
  'address' : IDL.Text,
  'slotNumber' : IDL.Text,
  'apartmentName' : IDL.Text,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addSlot' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Float64,
        IDL.Float64,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getSingleSlot' : IDL.Func([IDL.Nat], [IDL.Opt(ParkingSlot)], ['query']),
  'getSlotCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getSlots' : IDL.Func([IDL.Bool], [IDL.Vec(ParkingSlot)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'seedDemoSlots' : IDL.Func([], [], []),
  'toggleSlotAvailability' : IDL.Func([IDL.Nat, IDL.Text], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const ParkingSlot = IDL.Record({
    'id' : IDL.Nat,
    'lat' : IDL.Float64,
    'lng' : IDL.Float64,
    'contactInfo' : IDL.Text,
    'createdAt' : IDL.Int,
    'isAvailable' : IDL.Bool,
    'description' : IDL.Text,
    'ownerPin' : IDL.Text,
    'address' : IDL.Text,
    'slotNumber' : IDL.Text,
    'apartmentName' : IDL.Text,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addSlot' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Float64,
          IDL.Float64,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteSlot' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getSingleSlot' : IDL.Func([IDL.Nat], [IDL.Opt(ParkingSlot)], ['query']),
    'getSlotCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getSlots' : IDL.Func([IDL.Bool], [IDL.Vec(ParkingSlot)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'seedDemoSlots' : IDL.Func([], [], []),
    'toggleSlotAvailability' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  });
};

export const init = ({ IDL }) => { return []; };